### ISSUE TITLE
1.19.2 Large FPS Drop when using this mod

### ISSUE THREAD

**Issue by Saereth** [Hidoni/Transmog#1]
Forge 43.2.8
Mc 1.19.2
Current pack: FTB Skies

When adding transmog to the pack many players were reporting large framerate drops and upon investigating with spark and the ingame f3 menu to seems to be transmog is the primary culprit here. 

Here is the spark stack trace:
https://spark.lucko.me/iJhhQLZodA

If there is any other testing or data I can help provide let me know and I'll be more than glad to get together what I can for you. Thanks!

**Comment by Hidoni** [comment]
First of all, thanks for the report, the spark stack trace was really helpful!
I looked into more efficient ways for doing the checks that were killing performance. I'd appreciate if you could run the profiler again with the version below before I release it and let me know if it manages to lower the mod's performance hogging for you like it did for me!
[transmog-forge-1.2.1+1.19.2.zip](https://github.com/Hidoni/Transmog/files/11347427/transmog-forge-1.2.1%2B1.19.2.zip)

**Comment by Saereth** [comment]
several of our users tested and saw a significant performance increase so its looking good
![image](https://user-images.githubusercontent.com/9200909/234992247-d3dec32e-cbc0-4174-ab10-9df1d8187580.png)

**Comment by Hidoni** [comment]
Awesome, I'll go ahead and release a version with the fix for everyone then! ^^
