### ISSUE TITLE
Not seeing the recipe for Better MC (BMC4) on 1.20.1? 

### ISSUE THREAD

**Issue by anh9000** [Hidoni/Transmog#13]
![image](https://github.com/user-attachments/assets/f942c594-ce00-4e0a-83b7-9c9821abf05e)
![image](https://github.com/user-attachments/assets/65c93360-025b-4862-b7f3-333f06443f24)
![image](https://github.com/user-attachments/assets/2548f83a-6ec8-4716-91a7-58c0c112b49d)

This is on a multiplayer server, if I only have it client-side, I'm assuming it won't work as intended?

**Comment by Hidoni** [comment]
Yes, the mod will not work if it's not installed on the server you're playing on.
