### ISSUE TITLE
Compatibility issue with Vivecraft

### ISSUE THREAD

**Issue by fayer3** [Hidoni/Transmog#15]
Vivecraft calls GamerRendere.render() multiple times per frame, but only lets it run through once, which causes the renderCounter

https://github.com/Hidoni/Transmog/blob/2cca43060e1c9cf917131eac0dc5a518bc419844/Common/src/main/java/com/hidoni/transmog/RenderUtils.java#L6

to be out of whack and returning a fake inventory
https://github.com/Hidoni/Transmog/blob/2cca43060e1c9cf917131eac0dc5a518bc419844/Common/src/main/java/com/hidoni/transmog/mixin/PlayerMixin.java#L41

 when it shouldn't, causing the player to not be able to change items.

if you can't really fix that, I could add a call on our side to call this for everything that exits early https://github.com/Hidoni/Transmog/blob/2cca43060e1c9cf917131eac0dc5a518bc419844/Common/src/main/java/com/hidoni/transmog/RenderUtils.java#L14-L16

**Comment by Hidoni** [comment]
Interesting. Could you link me to the file where do you invoke `GameRenderer.render()` from in Vivecraft?  Depending on how you do it I might have to think of a more creative way to track the render state of the game

**Comment by fayer3** [comment]
https://github.com/Vivecraft/VivecraftMod/blob/cde85f81be498f9c9fc9c6368cdcef3cb2ba33bc/common/src/main/java/org/vivecraft/client_vr/render/helpers/VRPassHelper.java#L46

**Comment by Hidoni** [comment]
Took me a long time to get around to it, but I've just released a new version that might address this.  
If possible, I'd appreciate if you could check and let me know if that fixes the issue or not!

**Comment by fayer3** [comment]
looks like it works now.
