### ISSUE TITLE
[1.20.1-Forge] Huge FPS drops when using a transmogrified item.

### ISSUE THREAD

**Issue by Gbergz** [Hidoni/Transmog#2]
Title^

### **Versions:**
MC: 1.20.1
Forge: 47.1.3
Transmog: 1.2.3

Video: (FPS is in the top left corner.)
https://streamable.com/dfcd8c

**-** Gbergz

**Comment by Hidoni** [comment]
Hey there, thanks for the report!  
I can't reproduce this on my machine, so I'd appreciate it if you could attach a spark profiler report from your game.  
If you don't know how to do that, you can download spark from here: https://spark.lucko.me/download and then install it just like any other Forge mod. After installing it, run the command `/sparkc profiler start --timeout 15` and it will profile the performance of the game for 15 seconds, after which it will give you a link in the chat to the uploaded report!  
Just hold a transmogrified item during that time, and I'll be able to figure out what might be causing the FPS drops :)

**Comment by Gbergz** [comment]
Will do this. I'll get back to you.

**Comment by Gbergz** [comment]
https://spark.lucko.me/dDjKvKX5Z9

**Comment by Hidoni** [comment]
Thanks for the profiler results! I managed to replicate the issue (Seems it was the performance-inefficient checks that are negligent in a more vanilla enviornment compounded severly the more mods required them) and I have a version that seems to fix it, at least on my machine.
Could you try this version and tell me if it still impacts your FPS?  
[transmog-forge-1.2.4+1.20.zip](https://github.com/Hidoni/Transmog/files/12552487/transmog-forge-1.2.4%2B1.20.zip)

**Comment by Gbergz** [comment]
Seems **a lot** better from my testings.
Although there's still a small dip in the FPS, as it can be seen on the video below. Not as major at all.

Vid: https://streamable.com/x20wgc
New Profiler: https://spark.lucko.me/NnGdl5hS9J

Maybe it can't get any better than this since it's already A LOT better than before.
I am still very much pleased and thank you for the fix.

**Comment by Hidoni** [comment]
Hmm, does this version fix FPS drops for you?
[transmog-forge-1.2.4+1.20.zip](https://github.com/Hidoni/Transmog/files/12560586/transmog-forge-1.2.4%2B1.20.zip)

**Comment by Gbergz** [comment]
Tested it now and I am not sure if that made a difference, to be honest.

Definitely drops a bit. Maybe more than the previous one you sent? Not sure.

Anyway, vs the release one it's MILES better.

Vid: https://streamable.com/8024bf
New Profiler again: https://spark.lucko.me/tfEMVkXgzH

**Comment by Hidoni** [comment]
Well, I've made one final change that I'd appreciate you trying since it should improve the performance even more (though you don't have to!) [transmog-forge-1.2.4+1.20.zip](https://github.com/Hidoni/Transmog/files/12562158/transmog-forge-1.2.4%2B1.20.zip)  
I'm gonna go ahead and publish the version with these fixes soon, thanks for bringing this to my attention! :)

**Comment by Gbergz** [comment]
No problems! I will test it whenever I have time :)

**Comment by Gbergz** [comment]
It was better, thanks again :)

**Comment by Hidoni** [comment]
Awesome, thanks again for bringing the issue to my attention :)

**Comment by Gbergz** [comment]
No problems!
