### ISSUE TITLE
Does not work with Combat Roll enchantments

### ISSUE THREAD

**Issue by oinkratpig** [Hidoni/Transmog#4]
Doesn't seem to work with [Combat Roll](https://www.curseforge.com/minecraft/mc-mods/combat-roll) enchantments.

**Comment by Hidoni** [comment]
Hey, I just tested the mod on Fabric and it seemed to work perfectly fine, enchantments and all.  
Could you please let me know what version of Minecraft you're on and what version of both mods you're using, and are there any other mods installed alongside them? Thanks!

**Comment by oinkratpig** [comment]
Minecraft 1.20.1 Forge 47.1.3
Transmog 1.2.4+1.20

Mod list
https://pastebin.com/raw/14wLJM2r

Unfortunately because I'm using so many mods it's a bit hard to track down what could be causing it. If there's anything else I can do please let me know. [Here's a zip containing all of the mods](https://drive.google.com/file/d/19VpJzFqLcZ86th9iuNxd9QuvxeAms87h/view?usp=sharing).

**Comment by Hidoni** [comment]
I tried with all the mods and you're right, it doesn't work. But removing all mods except Transmog and Combat Roll makes it work again.  
Another mod from that mod list is causing the issue, but I have no idea which one it could be, and checking the logs doesn't seem to indicate anything that jumps out as problematic.  

Unfortunately I'm too busy at the moment to be able to check for the mods myself, but if you want to help, you can try searching for the mod that's causing the issue by taking out mods until you find that the enchantment works again and letting me know, that way I'd be able to check what specifically is going wrong and fix it :)

**Comment by Hidoni** [comment]
From my testing this appears to have been fixed in v1.3.0.
