### ISSUE TITLE
does not work with botania armor

### ISSUE THREAD

**Issue by Aoichides** [Hidoni/Transmog#8]
armor does not render or rather does not transmog at all

**Comment by Aoichides** [comment]
![not rendering](https://github.com/Hidoni/Transmog/assets/162269732/474fe809-8fe7-46a0-af26-9a61e153f76c)

**Comment by Hidoni** [comment]
![image](https://github.com/Hidoni/Transmog/assets/17706801/dbb29918-3d2f-4f72-8472-d46418266244)
Issue appears to be fixed on the latest version, so I'm closing this.  
If it still doesn't work for you please re-open it.
